-name: Code Scan and Fix

on:
  pull_request:
    branches:
      - main

jobs:
  run_security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run security-autopilot/securityai-github-action
      uses: security-autopilot/securityai-github-action@main
      with:
        args: >-
          --github_token ${{ secrets.GITHUB_TOKEN }}
          --repo_name ${{ github.repository }}
          --base_url https://security-autopilot-backend-prod-demo.azurewebsites.net
          --pr_number ${{ github.event.pull_request.number }}
          --threshold Low
